#!/bin/sh
echo "\e[1mCompiling $1 to C language\e[0m"

file_path=$1
file_ext="${file_path##*.}"

if [ "$file_ext" != "jaaa" ]; then
	echo "\e[91mError: only accept .jaaa files"
	return 1
fi

file_name="${file_path##*/}"
file_name="${file_name%.*}"
output_ext=".c"

./compiler > "$file_name$output_ext" < $1
echo "\e[32mThe output file is \e[1m$file_name$output_ext\e[0m"
return 0
